Repository openshift-online/ocm-api-model, pull requests merged in 2025-08, with the labels that each got.

#1081 OCM-15222 | feat: Added API for AutoNode Support
  clientapi/arohcp/v1alpha1/aws_auto_node_builder.go
  clientapi/arohcp/v1alpha1/aws_auto_node_list_builder.go
  clientapi/arohcp/v1alpha1/aws_auto_node_list_type_json.go
  clientapi/arohcp/v1alpha1/aws_auto_node_type.go
  clientapi/arohcp/v1alpha1/aws_auto_node_type_json.go
  clientapi/arohcp/v1alpha1/aws_builder.go
  clientapi/arohcp/v1alpha1/aws_type.go
  clientapi/arohcp/v1alpha1/aws_type_json.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_builder.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_list_builder.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_list_type_json.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_status_builder.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_status_list_builder.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_status_list_type_json.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_status_type.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_status_type_json.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_type.go
  clientapi/arohcp/v1alpha1/cluster_auto_node_type_json.go
  clientapi/arohcp/v1alpha1/cluster_builder.go
  clientapi/arohcp/v1alpha1/cluster_type.go
  clientapi/arohcp/v1alpha1/cluster_type_json.go
  clientapi/clustersmgmt/v1/aws_auto_node_builder.go
  clientapi/clustersmgmt/v1/aws_auto_node_list_builder.go
  clientapi/clustersmgmt/v1/aws_auto_node_list_type_json.go
  clientapi/clustersmgmt/v1/aws_auto_node_type.go
  clientapi/clustersmgmt/v1/aws_auto_node_type_json.go
  clientapi/clustersmgmt/v1/aws_builder.go
  clientapi/clustersmgmt/v1/aws_type.go
  clientapi/clustersmgmt/v1/aws_type_json.go
  clientapi/clustersmgmt/v1/cluster_auto_node_builder.go
  clientapi/clustersmgmt/v1/cluster_auto_node_list_builder.go
  clientapi/clustersmgmt/v1/cluster_auto_node_list_type_json.go
  clientapi/clustersmgmt/v1/cluster_auto_node_status_builder.go
  clientapi/clustersmgmt/v1/cluster_auto_node_status_list_builder.go
  clientapi/clustersmgmt/v1/cluster_auto_node_status_list_type_json.go
  clientapi/clustersmgmt/v1/cluster_auto_node_status_type.go
  clientapi/clustersmgmt/v1/cluster_auto_node_status_type_json.go
  clientapi/clustersmgmt/v1/cluster_auto_node_type.go
  clientapi/clustersmgmt/v1/cluster_auto_node_type_json.go
  clientapi/clustersmgmt/v1/cluster_builder.go
  clientapi/clustersmgmt/v1/cluster_type.go
  clientapi/clustersmgmt/v1/cluster_type_json.go
  model/clusters_mgmt/v1/aws_autonode_type.model
  model/clusters_mgmt/v1/aws_type.model
  model/clusters_mgmt/v1/cluster_autonode_type.model
  model/clusters_mgmt/v1/cluster_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: approved, lgtm

#1087 deprecate os disk configuration old design
  clientapi/arohcp/v1alpha1/azure_node_pool_builder.go
  clientapi/arohcp/v1alpha1/azure_node_pool_type.go
  clientapi/arohcp/v1alpha1/azure_node_pool_type_json.go
  clientapi/clustersmgmt/v1/azure_node_pool_builder.go
  clientapi/clustersmgmt/v1/azure_node_pool_type.go
  clientapi/clustersmgmt/v1/azure_node_pool_type_json.go
  model/clusters_mgmt/v1/azure_node_pool_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: ok-to-test, approved, lgtm

#1091 update CHANGES.md for a v0.0.430 tag/release
  CHANGES.md
Labels: approved, lgtm

#1094 update changes.md for v0.0.432
  CHANGES.md
Labels: approved, lgtm

#1095 Revert "update changes.md for v0.0.432"
  CHANGES.md
Labels: lgtm

#1097 update version in changes.md
  CHANGES.md
Labels: lgtm
