Repository openshift-online/ocm-api-model, pull requests merged in 2025-07, with the labels that each got.

#1062 ARO-19796: OCM API changes - mark cluster etcd_encryption flag as readonly
  clientapi/arohcp/v1alpha1/cluster_type.go
  clientapi/clustersmgmt/v1/cluster_type.go
  model/clusters_mgmt/v1/cluster_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: ok-to-test, approved, lgtm, jira/valid-reference

#1065 added ManagementCluster to AWSBackupConfig and changed BackupConfigs from map to list
  clientapi/arohcp/v1alpha1/aws_backup_config_builder.go
  clientapi/arohcp/v1alpha1/aws_backup_config_type.go
  clientapi/arohcp/v1alpha1/aws_backup_config_type_json.go
  clientapi/arohcp/v1alpha1/aws_shard_builder.go
  clientapi/arohcp/v1alpha1/aws_shard_type.go
  clientapi/arohcp/v1alpha1/aws_shard_type_json.go
  clientapi/clustersmgmt/v1/aws_backup_config_builder.go
  clientapi/clustersmgmt/v1/aws_backup_config_type.go
  clientapi/clustersmgmt/v1/aws_backup_config_type_json.go
  clientapi/clustersmgmt/v1/aws_shard_builder.go
  clientapi/clustersmgmt/v1/aws_shard_type.go
  clientapi/clustersmgmt/v1/aws_shard_type_json.go
  model/clusters_mgmt/v1/aws_backup_config_type.model
  model/clusters_mgmt/v1/aws_shard_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: approved, lgtm

#1063 [OCM-17005] define capacity reservation parameters in the AWSNodePool type
  clientapi/arohcp/v1alpha1/aws_capacity_reservation_builder.go
  clientapi/arohcp/v1alpha1/aws_capacity_reservation_list_builder.go
  clientapi/arohcp/v1alpha1/aws_capacity_reservation_list_type_json.go
  clientapi/arohcp/v1alpha1/aws_capacity_reservation_type.go
  clientapi/arohcp/v1alpha1/aws_capacity_reservation_type_json.go
  clientapi/arohcp/v1alpha1/aws_node_pool_builder.go
  clientapi/arohcp/v1alpha1/aws_node_pool_type.go
  clientapi/arohcp/v1alpha1/aws_node_pool_type_json.go
  clientapi/arohcp/v1alpha1/market_type_list_type_json.go
  clientapi/arohcp/v1alpha1/market_type_type.go
  clientapi/clustersmgmt/v1/aws_capacity_reservation_builder.go
  clientapi/clustersmgmt/v1/aws_capacity_reservation_list_builder.go
  clientapi/clustersmgmt/v1/aws_capacity_reservation_list_type_json.go
  clientapi/clustersmgmt/v1/aws_capacity_reservation_type.go
  clientapi/clustersmgmt/v1/aws_capacity_reservation_type_json.go
  clientapi/clustersmgmt/v1/aws_node_pool_builder.go
  clientapi/clustersmgmt/v1/aws_node_pool_type.go
  clientapi/clustersmgmt/v1/aws_node_pool_type_json.go
  clientapi/clustersmgmt/v1/market_type_list_type_json.go
  clientapi/clustersmgmt/v1/market_type_type.go
  model/clusters_mgmt/v1/aws_capacity_reservation_type.model
  model/clusters_mgmt/v1/aws_node_pool_type.model
  model/clusters_mgmt/v1/market_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: ok-to-test, approved, lgtm

#1070 ARO-19120 | Cluster image registry - improve documentation
  clientapi/arohcp/v1alpha1/cluster_type.go
  clientapi/clustersmgmt/v1/cluster_type.go
  model/clusters_mgmt/v1/cluster_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: approved, lgtm

#1075 OCM-15598 | Add fields for federated project
  clientapi/clustersmgmt/v1/wif_gcp_builder.go
  clientapi/clustersmgmt/v1/wif_gcp_type.go
  clientapi/clustersmgmt/v1/wif_gcp_type_json.go
  model/clusters_mgmt/v1/wif_config_type.model
  openapi/clusters_mgmt/v1/openapi.json
Labels: lgtm

#1079 OCM-17429 | chore: Update README to document the use of @deprecated annotation
  README.md
Labels: approved, lgtm
