Repository openshift-online/ocm-api-model, pull requests merged in 2025-06, with the labels that each got.

#1044 update gh setup-python to latest version
  .github/workflows/publish-release.yaml
Labels: approved, lgtm

#1043 Bump metamodel version to v0.0.68
  Makefile
Labels: approved, lgtm

#1045 Release v0.0.418 CHANGES
  CHANGES.md
Labels: needs-ok-to-test, approved, lgtm

#1048 add macgregor, cristianoveiga to owners/approvers
  OWNERS
Labels: approved, lgtm

#1042 Remove old github workflows that have been replaced by prow
  .github/workflows/check-pull-request.yaml
Labels: approved, lgtm

#1040 feat: add azure managed identities requirements endpoints
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_builder.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_list_builder.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_list_type_json.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_type.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_type_json.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_builder.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_list_builder.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_list_type_json.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_type.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_type_json.go
  clientapi/arohcp/v1alpha1/identity_service_account_builder.go
  clientapi/arohcp/v1alpha1/identity_service_account_list_builder.go
  clientapi/arohcp/v1alpha1/identity_service_account_list_type_json.go
  clientapi/arohcp/v1alpha1/identity_service_account_type.go
  clientapi/arohcp/v1alpha1/identity_service_account_type_json.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_builder.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_list_builder.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_list_type_json.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_type.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_type_json.go
  clientapi/arohcp/v1alpha1/role_definition_builder.go
  clientapi/arohcp/v1alpha1/role_definition_list_builder.go
  clientapi/arohcp/v1alpha1/role_definition_list_type_json.go
  clientapi/arohcp/v1alpha1/role_definition_type.go
  clientapi/arohcp/v1alpha1/role_definition_type_json.go
  model/aro_hcp/v1alpha1/managed_identities_requirements_resource.model
  model/aro_hcp/v1alpha1/managed_identities_requirements_type.model
  model/aro_hcp/v1alpha1/root_resource.model
  openapi/aro_hcp/v1alpha1/openapi.json
Labels: approved, lgtm

#1051 ARO-15234: Review namings of managed identities requirement types.
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_list_builder.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_requirement_builder.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_requirement_list_builder.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_requirement_list_type_json.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_requirement_type.go
  clientapi/arohcp/v1alpha1/control_plane_operator_identity_requirement_type_json.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_list_builder.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_requirement_builder.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_requirement_list_builder.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_requirement_list_type_json.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_requirement_type.go
  clientapi/arohcp/v1alpha1/data_plane_operator_identity_requirement_type_json.go
  clientapi/arohcp/v1alpha1/identity_service_account_list_builder.go
  clientapi/arohcp/v1alpha1/k8s_service_account_operator_identity_requirement_builder.go
  clientapi/arohcp/v1alpha1/k8s_service_account_operator_identity_requirement_list_builder.go
  clientapi/arohcp/v1alpha1/k8s_service_account_operator_identity_requirement_list_type_json.go
  clientapi/arohcp/v1alpha1/k8s_service_account_operator_identity_requirement_type.go
  clientapi/arohcp/v1alpha1/k8s_service_account_operator_identity_requirement_type_json.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_builder.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_type.go
  clientapi/arohcp/v1alpha1/managed_identities_requirements_type_json.go
  clientapi/arohcp/v1alpha1/role_definition_list_builder.go
  clientapi/arohcp/v1alpha1/role_definition_operator_identity_requirement_builder.go
  clientapi/arohcp/v1alpha1/role_definition_operator_identity_requirement_list_builder.go
  clientapi/arohcp/v1alpha1/role_definition_operator_identity_requirement_list_type_json.go
  clientapi/arohcp/v1alpha1/role_definition_operator_identity_requirement_type.go
  clientapi/arohcp/v1alpha1/role_definition_operator_identity_requirement_type_json.go
  model/aro_hcp/v1alpha1/managed_identities_requirements_resource.model
  model/aro_hcp/v1alpha1/managed_identities_requirements_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
Labels: approved, lgtm, jira/valid-reference

#1049 feat: update aro_hcp/v1alpha1 add nodepools to be async
  metamodel_generator/go.mod
  metamodel_generator/go.sum
  model/aro_hcp/v1alpha1/cluster_resource.model
  model/aro_hcp/v1alpha1/clusters_resource.model
  model/aro_hcp/v1alpha1/node_pools_resource.model
  openapi/aro_hcp/v1alpha1/openapi.json
Labels: needs-ok-to-test, approved, lgtm

#1052 OCM-15784: adding AWSBackupConfig type and included it in AWSShard model
  clientapi/arohcp/v1alpha1/aws_backup_config_builder.go
  clientapi/arohcp/v1alpha1/aws_backup_config_list_builder.go
  clientapi/arohcp/v1alpha1/aws_backup_config_list_type_json.go
  clientapi/arohcp/v1alpha1/aws_backup_config_type.go
  clientapi/arohcp/v1alpha1/aws_backup_config_type_json.go
  clientapi/arohcp/v1alpha1/aws_shard_builder.go
  clientapi/arohcp/v1alpha1/aws_shard_type.go
  clientapi/arohcp/v1alpha1/aws_shard_type_json.go
  clientapi/clustersmgmt/v1/aws_backup_config_builder.go
  clientapi/clustersmgmt/v1/aws_backup_config_list_builder.go
  clientapi/clustersmgmt/v1/aws_backup_config_list_type_json.go
  clientapi/clustersmgmt/v1/aws_backup_config_type.go
  clientapi/clustersmgmt/v1/aws_backup_config_type_json.go
  clientapi/clustersmgmt/v1/aws_shard_builder.go
  clientapi/clustersmgmt/v1/aws_shard_type.go
  clientapi/clustersmgmt/v1/aws_shard_type_json.go
  model/clusters_mgmt/v1/aws_backup_config_type.model
  model/clusters_mgmt/v1/aws_shard_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: approved, lgtm, jira/valid-reference

#1056 updated changes.md for release 0.0.420
  CHANGES.md
Labels: approved, lgtm

#1054 model changes for async cluster updates
  clientapi/arohcp/v1alpha1/cluster_state_type.go
  clientapi/clustersmgmt/v1/cluster_state_type.go
  model/aro_hcp/v1alpha1/cluster_resource.model
  model/clusters_mgmt/v1/cluster_state_type.model
  openapi/aro_hcp/v1alpha1/openapi.json
  openapi/clusters_mgmt/v1/openapi.json
Labels: ok-to-test, lgtm

#1057 Add license.txt to see if pkg.go.dev likes it better
  Makefile
  clientapi/LICENSE.txt
Labels: approved, lgtm
